version: '3'
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - type: bind
        source: "./"
        target: "/code"
    command: tail -f /dev/null
